# Generated by Django 4.1.6 on 2023-02-04 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='', regex='')])),
                ('persons', models.SmallIntegerField()),
                ('message', models.TextField(blank=True, max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('date_priccessing', models.DateField(auto_now=True)),
                ('is_proccessed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.DeleteModel(
            name='Specials',
        ),
        migrations.AlterField(
            model_name='events',
            name='photo',
            field=models.ImageField(blank=True, upload_to='events/%Y_%m_%d'),
        ),
    ]
