# Generated by Django 4.1.6 on 2023-02-08 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_reservation_delete_specials_alter_events_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date_priccessing',
            new_name='date_proccessing',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Error phone number', regex='^\\+?3?8?0\\d{2}[- ]?(\\d[- ]?){7}$')]),
        ),
    ]
